# Generated by Django 5.2.7 on 2025-10-21 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_reaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='enable_notifications',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='notification_sound',
            field=models.BooleanField(default=True),
        ),
    ]
